---
title: "edld610_lab1"
author: "Cameron Kay, Lea Frank, and Ashley Miller"
date: "1/9/2019"
output:
  html_document:
    highlight: zenburn
    theme: lumen
    toc: yes
    toc_depth: 4
    toc_float: yes
---

```{r setup, include=FALSE}
#load packages
library(rio)
library(here)
library(tidyverse)
library(lubridate)

#load data
df <- import(here::here("data", "rstats_tweets.rds")) %>%
  janitor::clean_names()
```

```{r commit2}
df %>%
  count(screen_name) %>%
  arrange(desc(n)) %>%
  dplyr::slice(1:25) %>%
  mutate(screen_name = factor(screen_name)) %>%
  ggplot(aes(x = forcats::fct_reorder(screen_name, n), y = n)) +
    geom_col() +
    coord_flip()
```

```{r commit3, fig.width = 10, fig.height = 10}
df %>%
  count(screen_name) %>%
  arrange(desc(n)) %>%
  dplyr::slice(1:25) %>%
  mutate(screen_name = factor(screen_name)) %>%
  ggplot(aes(x = forcats::fct_reorder(screen_name, n), y = n)) +
    geom_col(fill = "cornflowerblue", alpha = .8) +
    coord_flip() +
    theme_minimal(base_size = 15) +
    labs(title    = "Most prolific #rstats tweets",
         subtitle = "Top 25 screen names displayed",
         y        = "Count",
         x        = "Twitter Screen Name",
         caption  = "Data from Mike Kearny, distributed via #tidytuesday")
```

```{r commit4}
# Commit 4
df$month <- round_date(df$created_at, unit = "month")
df <- df %>% 
  filter(month < as_datetime("2019-01-01"))

numtweets <- df %>% 
  group_by(month) %>% 
  count()

numtweets %>% 
  ggplot(aes(x = month, y = n)) +
  geom_line() +
  geom_smooth()
```

Modify the plot so it matches the below.
Use theme_minimal
Add the area with the appropriate function and 30% transparency
Use "gray40", "cornflowerblue", and "magenta"


```{r commit5, fig.width = 10, fig.height = 10}
numtweets %>% 
  ggplot(aes(x = month, y = n)) +
  geom_area(stat = "identity", fill = "cornflowerblue", alpha = .3) +
  geom_line(color = "gray40", size = 1.5) +
  geom_smooth(se = FALSE, color = "magenta", size = 1.5) +
  theme_minimal(base_size = 18) +
  labs(y = "Number of #rstat tweets", 
       x = "Year (summarized by month)",
       title = "Growth of the #rstats hashtag on twitter over time",
       caption = "Data from Mike Kearny, distributed via #tidytuesday")
```





